const fs = require("fs");
const p = "d:/РАБОТА/111 ПОРТАЛ ,,, ПРОЕКТ РАСКРУТОВ 05,2026 111/raskrutov-kz-2026/site_mirror/web-studiya/kontekstnaya-reklama/google-ads/index.html";
const t = fs.readFileSync(p, "utf8");
const m = t.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
const j = JSON.parse(m[1]);
console.log("graph types", j["@graph"].map(x => (Array.isArray(x["@type"]) ? x["@type"].join(",") : x["@type"]) + " " + (x["@id"] || "")));
const faq = j["@graph"].find(x => x["@type"] === "FAQPage");
console.log("faq count", faq.mainEntity.length);
console.log("faq @id", faq["@id"]);
faq.mainEntity.forEach((q, i) => console.log((i + 1) + ". " + q.name));
console.log("lead-forms print", /lead-forms\.css" media="print"/.test(t));
console.log("consent contacts", t.includes("gads-contact-regulation"));
console.log("timeout 1800", t.includes("timeout: 1800"));
console.log("timeout 4000", t.includes("timeout: 4000"));
console.log("Google Ads", (t.match(/Google Ads/g) || []).length);
console.log("Kazakhstan", (t.match(/Казахстан/g) || []).length);
console.log("PMax", (t.match(/Performance Max/g) || []).length);
console.log("details", (t.match(/<details/g) || []).length);
const hi = t.indexOf("rk-hero__lead");
console.log(t.slice(hi, hi + 350));
